### ISSUE TITLE
code duplication

### ISSUE THREAD

**Issue by maxbiostat** [GuidoAMoreira/stan_summer#2]
Is [this](https://github.com/GuidoAMoreira/stan_summer/blob/main/n_mixture/infiniteSumToThreshold.stan) file necessary or can it be called from elsewhere in the repo?

**Comment by GuidoAMoreira** [comment]
Please be more specific.

**Comment by maxbiostat** [comment]
It's the same code as in [here](https://github.com/GuidoAMoreira/stan_summer/blob/main/stan/infiniteSumToThreshold.stan).

**Comment by GuidoAMoreira** [comment]
The function has been slightly modified for efficiency.

**Comment by maxbiostat** [comment]
OkDOK
